<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccountingApp.Application\AccountingApp.Application.csproj" />
    <ProjectReference Include="..\AccountingApp.Infrastructure\AccountingApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
